name: Informe Semanal LaLiga
on:
  schedule:
    - cron: '0 8 * * 1' # Cada lunes a las 8am
  workflow_dispatch: # Para lanzarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python main.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Nuevo informe semanal LaLiga"
